name: tanuki
description: Graphical interface for tanuki digital asset management.
version: 1.0.0+1
homepage: https://github.com/nlfiedler/tanuki
repository: https://github.com/nlfiedler/tanuki.git
issue_tracker: https://github.com/nlfiedler/tanuki/issues
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^1.2.3
  file_picker: ^1.13.3
  file_picker_web: ^1.0.2+1
  flutter_bloc: ^6.0.1
  # temporary solution for desktop file chooser (no package yet available)
  file_chooser:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
      ref: 927f8cbc09b35d85245c095f2db8df9b186f6618
  flutter_dropzone: ^1.0.9
  # workaround for https://github.com/danvick/flutter_form_builder/issues/382
  # flutter_form_builder: ^3.14.0-alpha.2
  # workaround for https://github.com/danvick/flutter_form_builder/issues/465
  flutter_form_builder:
    git:
      url: https://github.com/knaeckeKami/flutter_form_builder.git
      ref: v3.14.0-alpha.2-fix
  get_it: ^4.0.4
  graphql: ^3.1.0
  http: ^0.12.2
  intl: ^0.16.1
  mime_type: ^0.3.2
  oxidized: ^3.1.0
  path: ^1.7.0
  url_launcher: ^5.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^7.0.0
  environment_config: ^2.2.3
  # mockito 4.1.2 breaks bloc_test (https://github.com/felangel/bloc/issues/1676)
  # (issue is marked fixed but still not released)
  mockito: 4.1.1
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

environment_config:
  const: true
  fields:
    base_url:
      default: http://127.0.0.1:3000
      env_var: BASE_URL
