name: tanuki
description: Personal digital asset management system.
version: 1.0.0+1
homepage: https://github.com/nlfiedler/tanuki
repository: https://github.com/nlfiedler/tanuki.git
issue_tracker: https://github.com/nlfiedler/tanuki/issues
publish_to: 'none'

environment:
  sdk: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter

  bloc_concurrency: ^0.2.0
  bloc: ^8.1.1
  choose_input_chips: ^1.1.0
  equatable: ^2.0.0
  file_selector_macos: ^0.9.0+4
  file_selector_web: ^0.9.0+2
  file_selector: ^0.9.2+2
  flutter_bloc: ^8.0.1
  flutter_dropzone: ^3.0.5
  flutter_form_builder: ^7.7.0
  flutter_riverpod: ^2.2.0
  flutter_typeahead: ^4.3.7
  form_builder_validators: ^8.4.0
  graphql: ^5.1.3
  http_parser: ^4.0.2
  http: ^0.13.2
  intl: ^0.17.0
  mime: ^1.0.4
  multi_tag_picker: ^1.0.0
  oxidized: ^5.2.0
  path: ^1.8.0
  responsive_framework: ^0.2.0
  url_launcher: ^6.1.9
  video_player: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.0.3
  environment_config: ^3.0.0
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - public/images/tanuki.png
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

environment_config:
  const: true
  fields:
    base_url:
      default: http://127.0.0.1:3000
      env_var: BASE_URL
