name: tanuki
description: Graphical interface for tanuki digital asset management.
version: 1.0.0+1
homepage: https://github.com/nlfiedler/tanuki
repository: https://github.com/nlfiedler/tanuki.git
issue_tracker: https://github.com/nlfiedler/tanuki/issues
publish_to: 'none'

environment:
  sdk: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter

  bloc_concurrency: ^0.2.0
  equatable: ^2.0.0
  file_selector: ^0.8.4
  file_selector_macos: ^0.8.2
  file_selector_web: ^0.8.1
  form_builder_validators: ^7.6.1
  flutter_bloc: ^8.0.1
  # lock on 1.9.3 for https://github.com/danvick/flutter_chips_input/issues/66
  flutter_chips_input: 1.9.3
  flutter_dropzone: ^3.0.5
  # lock on 7.1.1 for https://github.com/danvick/flutter_form_builder/issues/1028
  flutter_form_builder: 7.1.1
  flutter_riverpod: ^1.0.3
  graphql: ^5.0.0
  http: ^0.13.2
  intl: ^0.17.0
  mime: ^1.0.0
  oxidized: ^5.2.0
  path: ^1.8.0
  responsive_framework: ^0.1.9
  url_launcher: ^6.0.3
  video_player: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.0.3
  environment_config: ^3.0.0
  flutter_lints: ^1.0.4
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - public/images/tanuki.png
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

environment_config:
  const: true
  fields:
    base_url:
      default: http://127.0.0.1:3000
      env_var: BASE_URL
